
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TasksCollection` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TasksCollection
 * 
 */
export type TasksCollectionModel = runtime.Types.Result.DefaultSelection<Prisma.$TasksCollectionPayload>

export type AggregateTasksCollection = {
  _count: TasksCollectionCountAggregateOutputType | null
  _min: TasksCollectionMinAggregateOutputType | null
  _max: TasksCollectionMaxAggregateOutputType | null
}

export type TasksCollectionMinAggregateOutputType = {
  tasksId: string | null
  tasksName: string | null
  details: string | null
  created: Date | null
  due: Date | null
  updated: Date | null
}

export type TasksCollectionMaxAggregateOutputType = {
  tasksId: string | null
  tasksName: string | null
  details: string | null
  created: Date | null
  due: Date | null
  updated: Date | null
}

export type TasksCollectionCountAggregateOutputType = {
  tasksId: number
  tasksName: number
  details: number
  created: number
  due: number
  updated: number
  _all: number
}


export type TasksCollectionMinAggregateInputType = {
  tasksId?: true
  tasksName?: true
  details?: true
  created?: true
  due?: true
  updated?: true
}

export type TasksCollectionMaxAggregateInputType = {
  tasksId?: true
  tasksName?: true
  details?: true
  created?: true
  due?: true
  updated?: true
}

export type TasksCollectionCountAggregateInputType = {
  tasksId?: true
  tasksName?: true
  details?: true
  created?: true
  due?: true
  updated?: true
  _all?: true
}

export type TasksCollectionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TasksCollection to aggregate.
   */
  where?: Prisma.TasksCollectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TasksCollections to fetch.
   */
  orderBy?: Prisma.TasksCollectionOrderByWithRelationInput | Prisma.TasksCollectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TasksCollectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TasksCollections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TasksCollections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TasksCollections
  **/
  _count?: true | TasksCollectionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TasksCollectionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TasksCollectionMaxAggregateInputType
}

export type GetTasksCollectionAggregateType<T extends TasksCollectionAggregateArgs> = {
      [P in keyof T & keyof AggregateTasksCollection]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTasksCollection[P]>
    : Prisma.GetScalarType<T[P], AggregateTasksCollection[P]>
}




export type TasksCollectionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TasksCollectionWhereInput
  orderBy?: Prisma.TasksCollectionOrderByWithAggregationInput | Prisma.TasksCollectionOrderByWithAggregationInput[]
  by: Prisma.TasksCollectionScalarFieldEnum[] | Prisma.TasksCollectionScalarFieldEnum
  having?: Prisma.TasksCollectionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TasksCollectionCountAggregateInputType | true
  _min?: TasksCollectionMinAggregateInputType
  _max?: TasksCollectionMaxAggregateInputType
}

export type TasksCollectionGroupByOutputType = {
  tasksId: string
  tasksName: string
  details: string
  created: Date
  due: Date
  updated: Date
  _count: TasksCollectionCountAggregateOutputType | null
  _min: TasksCollectionMinAggregateOutputType | null
  _max: TasksCollectionMaxAggregateOutputType | null
}

type GetTasksCollectionGroupByPayload<T extends TasksCollectionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TasksCollectionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TasksCollectionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TasksCollectionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TasksCollectionGroupByOutputType[P]>
      }
    >
  >



export type TasksCollectionWhereInput = {
  AND?: Prisma.TasksCollectionWhereInput | Prisma.TasksCollectionWhereInput[]
  OR?: Prisma.TasksCollectionWhereInput[]
  NOT?: Prisma.TasksCollectionWhereInput | Prisma.TasksCollectionWhereInput[]
  tasksId?: Prisma.UuidFilter<"TasksCollection"> | string
  tasksName?: Prisma.StringFilter<"TasksCollection"> | string
  details?: Prisma.StringFilter<"TasksCollection"> | string
  created?: Prisma.DateTimeFilter<"TasksCollection"> | Date | string
  due?: Prisma.DateTimeFilter<"TasksCollection"> | Date | string
  updated?: Prisma.DateTimeFilter<"TasksCollection"> | Date | string
  tasks?: Prisma.TaskListRelationFilter
}

export type TasksCollectionOrderByWithRelationInput = {
  tasksId?: Prisma.SortOrder
  tasksName?: Prisma.SortOrder
  details?: Prisma.SortOrder
  created?: Prisma.SortOrder
  due?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  tasks?: Prisma.TaskOrderByRelationAggregateInput
}

export type TasksCollectionWhereUniqueInput = Prisma.AtLeast<{
  tasksId?: string
  AND?: Prisma.TasksCollectionWhereInput | Prisma.TasksCollectionWhereInput[]
  OR?: Prisma.TasksCollectionWhereInput[]
  NOT?: Prisma.TasksCollectionWhereInput | Prisma.TasksCollectionWhereInput[]
  tasksName?: Prisma.StringFilter<"TasksCollection"> | string
  details?: Prisma.StringFilter<"TasksCollection"> | string
  created?: Prisma.DateTimeFilter<"TasksCollection"> | Date | string
  due?: Prisma.DateTimeFilter<"TasksCollection"> | Date | string
  updated?: Prisma.DateTimeFilter<"TasksCollection"> | Date | string
  tasks?: Prisma.TaskListRelationFilter
}, "tasksId">

export type TasksCollectionOrderByWithAggregationInput = {
  tasksId?: Prisma.SortOrder
  tasksName?: Prisma.SortOrder
  details?: Prisma.SortOrder
  created?: Prisma.SortOrder
  due?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  _count?: Prisma.TasksCollectionCountOrderByAggregateInput
  _max?: Prisma.TasksCollectionMaxOrderByAggregateInput
  _min?: Prisma.TasksCollectionMinOrderByAggregateInput
}

export type TasksCollectionScalarWhereWithAggregatesInput = {
  AND?: Prisma.TasksCollectionScalarWhereWithAggregatesInput | Prisma.TasksCollectionScalarWhereWithAggregatesInput[]
  OR?: Prisma.TasksCollectionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TasksCollectionScalarWhereWithAggregatesInput | Prisma.TasksCollectionScalarWhereWithAggregatesInput[]
  tasksId?: Prisma.UuidWithAggregatesFilter<"TasksCollection"> | string
  tasksName?: Prisma.StringWithAggregatesFilter<"TasksCollection"> | string
  details?: Prisma.StringWithAggregatesFilter<"TasksCollection"> | string
  created?: Prisma.DateTimeWithAggregatesFilter<"TasksCollection"> | Date | string
  due?: Prisma.DateTimeWithAggregatesFilter<"TasksCollection"> | Date | string
  updated?: Prisma.DateTimeWithAggregatesFilter<"TasksCollection"> | Date | string
}

export type TasksCollectionCreateInput = {
  tasksId?: string
  tasksName: string
  details: string
  created?: Date | string
  due: Date | string
  updated?: Date | string
  tasks?: Prisma.TaskCreateNestedManyWithoutCollectionInput
}

export type TasksCollectionUncheckedCreateInput = {
  tasksId?: string
  tasksName: string
  details: string
  created?: Date | string
  due: Date | string
  updated?: Date | string
  tasks?: Prisma.TaskUncheckedCreateNestedManyWithoutCollectionInput
}

export type TasksCollectionUpdateInput = {
  tasksId?: Prisma.StringFieldUpdateOperationsInput | string
  tasksName?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  due?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tasks?: Prisma.TaskUpdateManyWithoutCollectionNestedInput
}

export type TasksCollectionUncheckedUpdateInput = {
  tasksId?: Prisma.StringFieldUpdateOperationsInput | string
  tasksName?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  due?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tasks?: Prisma.TaskUncheckedUpdateManyWithoutCollectionNestedInput
}

export type TasksCollectionCreateManyInput = {
  tasksId?: string
  tasksName: string
  details: string
  created?: Date | string
  due: Date | string
  updated?: Date | string
}

export type TasksCollectionUpdateManyMutationInput = {
  tasksId?: Prisma.StringFieldUpdateOperationsInput | string
  tasksName?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  due?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TasksCollectionUncheckedUpdateManyInput = {
  tasksId?: Prisma.StringFieldUpdateOperationsInput | string
  tasksName?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  due?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TasksCollectionCountOrderByAggregateInput = {
  tasksId?: Prisma.SortOrder
  tasksName?: Prisma.SortOrder
  details?: Prisma.SortOrder
  created?: Prisma.SortOrder
  due?: Prisma.SortOrder
  updated?: Prisma.SortOrder
}

export type TasksCollectionMaxOrderByAggregateInput = {
  tasksId?: Prisma.SortOrder
  tasksName?: Prisma.SortOrder
  details?: Prisma.SortOrder
  created?: Prisma.SortOrder
  due?: Prisma.SortOrder
  updated?: Prisma.SortOrder
}

export type TasksCollectionMinOrderByAggregateInput = {
  tasksId?: Prisma.SortOrder
  tasksName?: Prisma.SortOrder
  details?: Prisma.SortOrder
  created?: Prisma.SortOrder
  due?: Prisma.SortOrder
  updated?: Prisma.SortOrder
}

export type TasksCollectionScalarRelationFilter = {
  is?: Prisma.TasksCollectionWhereInput
  isNot?: Prisma.TasksCollectionWhereInput
}

export type TasksCollectionCreateNestedOneWithoutTasksInput = {
  create?: Prisma.XOR<Prisma.TasksCollectionCreateWithoutTasksInput, Prisma.TasksCollectionUncheckedCreateWithoutTasksInput>
  connectOrCreate?: Prisma.TasksCollectionCreateOrConnectWithoutTasksInput
  connect?: Prisma.TasksCollectionWhereUniqueInput
}

export type TasksCollectionUpdateOneRequiredWithoutTasksNestedInput = {
  create?: Prisma.XOR<Prisma.TasksCollectionCreateWithoutTasksInput, Prisma.TasksCollectionUncheckedCreateWithoutTasksInput>
  connectOrCreate?: Prisma.TasksCollectionCreateOrConnectWithoutTasksInput
  upsert?: Prisma.TasksCollectionUpsertWithoutTasksInput
  connect?: Prisma.TasksCollectionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TasksCollectionUpdateToOneWithWhereWithoutTasksInput, Prisma.TasksCollectionUpdateWithoutTasksInput>, Prisma.TasksCollectionUncheckedUpdateWithoutTasksInput>
}

export type TasksCollectionCreateWithoutTasksInput = {
  tasksId?: string
  tasksName: string
  details: string
  created?: Date | string
  due: Date | string
  updated?: Date | string
}

export type TasksCollectionUncheckedCreateWithoutTasksInput = {
  tasksId?: string
  tasksName: string
  details: string
  created?: Date | string
  due: Date | string
  updated?: Date | string
}

export type TasksCollectionCreateOrConnectWithoutTasksInput = {
  where: Prisma.TasksCollectionWhereUniqueInput
  create: Prisma.XOR<Prisma.TasksCollectionCreateWithoutTasksInput, Prisma.TasksCollectionUncheckedCreateWithoutTasksInput>
}

export type TasksCollectionUpsertWithoutTasksInput = {
  update: Prisma.XOR<Prisma.TasksCollectionUpdateWithoutTasksInput, Prisma.TasksCollectionUncheckedUpdateWithoutTasksInput>
  create: Prisma.XOR<Prisma.TasksCollectionCreateWithoutTasksInput, Prisma.TasksCollectionUncheckedCreateWithoutTasksInput>
  where?: Prisma.TasksCollectionWhereInput
}

export type TasksCollectionUpdateToOneWithWhereWithoutTasksInput = {
  where?: Prisma.TasksCollectionWhereInput
  data: Prisma.XOR<Prisma.TasksCollectionUpdateWithoutTasksInput, Prisma.TasksCollectionUncheckedUpdateWithoutTasksInput>
}

export type TasksCollectionUpdateWithoutTasksInput = {
  tasksId?: Prisma.StringFieldUpdateOperationsInput | string
  tasksName?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  due?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TasksCollectionUncheckedUpdateWithoutTasksInput = {
  tasksId?: Prisma.StringFieldUpdateOperationsInput | string
  tasksName?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  due?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TasksCollectionCountOutputType
 */

export type TasksCollectionCountOutputType = {
  tasks: number
}

export type TasksCollectionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tasks?: boolean | TasksCollectionCountOutputTypeCountTasksArgs
}

/**
 * TasksCollectionCountOutputType without action
 */
export type TasksCollectionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TasksCollectionCountOutputType
   */
  select?: Prisma.TasksCollectionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TasksCollectionCountOutputType without action
 */
export type TasksCollectionCountOutputTypeCountTasksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TaskWhereInput
}


export type TasksCollectionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tasksId?: boolean
  tasksName?: boolean
  details?: boolean
  created?: boolean
  due?: boolean
  updated?: boolean
  tasks?: boolean | Prisma.TasksCollection$tasksArgs<ExtArgs>
  _count?: boolean | Prisma.TasksCollectionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tasksCollection"]>

export type TasksCollectionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tasksId?: boolean
  tasksName?: boolean
  details?: boolean
  created?: boolean
  due?: boolean
  updated?: boolean
}, ExtArgs["result"]["tasksCollection"]>

export type TasksCollectionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tasksId?: boolean
  tasksName?: boolean
  details?: boolean
  created?: boolean
  due?: boolean
  updated?: boolean
}, ExtArgs["result"]["tasksCollection"]>

export type TasksCollectionSelectScalar = {
  tasksId?: boolean
  tasksName?: boolean
  details?: boolean
  created?: boolean
  due?: boolean
  updated?: boolean
}

export type TasksCollectionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"tasksId" | "tasksName" | "details" | "created" | "due" | "updated", ExtArgs["result"]["tasksCollection"]>
export type TasksCollectionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tasks?: boolean | Prisma.TasksCollection$tasksArgs<ExtArgs>
  _count?: boolean | Prisma.TasksCollectionCountOutputTypeDefaultArgs<ExtArgs>
}
export type TasksCollectionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type TasksCollectionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $TasksCollectionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TasksCollection"
  objects: {
    tasks: Prisma.$TaskPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    tasksId: string
    tasksName: string
    details: string
    created: Date
    due: Date
    updated: Date
  }, ExtArgs["result"]["tasksCollection"]>
  composites: {}
}

export type TasksCollectionGetPayload<S extends boolean | null | undefined | TasksCollectionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TasksCollectionPayload, S>

export type TasksCollectionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TasksCollectionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TasksCollectionCountAggregateInputType | true
  }

export interface TasksCollectionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TasksCollection'], meta: { name: 'TasksCollection' } }
  /**
   * Find zero or one TasksCollection that matches the filter.
   * @param {TasksCollectionFindUniqueArgs} args - Arguments to find a TasksCollection
   * @example
   * // Get one TasksCollection
   * const tasksCollection = await prisma.tasksCollection.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TasksCollectionFindUniqueArgs>(args: Prisma.SelectSubset<T, TasksCollectionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TasksCollectionClient<runtime.Types.Result.GetResult<Prisma.$TasksCollectionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TasksCollection that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TasksCollectionFindUniqueOrThrowArgs} args - Arguments to find a TasksCollection
   * @example
   * // Get one TasksCollection
   * const tasksCollection = await prisma.tasksCollection.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TasksCollectionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TasksCollectionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TasksCollectionClient<runtime.Types.Result.GetResult<Prisma.$TasksCollectionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TasksCollection that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TasksCollectionFindFirstArgs} args - Arguments to find a TasksCollection
   * @example
   * // Get one TasksCollection
   * const tasksCollection = await prisma.tasksCollection.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TasksCollectionFindFirstArgs>(args?: Prisma.SelectSubset<T, TasksCollectionFindFirstArgs<ExtArgs>>): Prisma.Prisma__TasksCollectionClient<runtime.Types.Result.GetResult<Prisma.$TasksCollectionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TasksCollection that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TasksCollectionFindFirstOrThrowArgs} args - Arguments to find a TasksCollection
   * @example
   * // Get one TasksCollection
   * const tasksCollection = await prisma.tasksCollection.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TasksCollectionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TasksCollectionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TasksCollectionClient<runtime.Types.Result.GetResult<Prisma.$TasksCollectionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TasksCollections that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TasksCollectionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TasksCollections
   * const tasksCollections = await prisma.tasksCollection.findMany()
   * 
   * // Get first 10 TasksCollections
   * const tasksCollections = await prisma.tasksCollection.findMany({ take: 10 })
   * 
   * // Only select the `tasksId`
   * const tasksCollectionWithTasksIdOnly = await prisma.tasksCollection.findMany({ select: { tasksId: true } })
   * 
   */
  findMany<T extends TasksCollectionFindManyArgs>(args?: Prisma.SelectSubset<T, TasksCollectionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TasksCollectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TasksCollection.
   * @param {TasksCollectionCreateArgs} args - Arguments to create a TasksCollection.
   * @example
   * // Create one TasksCollection
   * const TasksCollection = await prisma.tasksCollection.create({
   *   data: {
   *     // ... data to create a TasksCollection
   *   }
   * })
   * 
   */
  create<T extends TasksCollectionCreateArgs>(args: Prisma.SelectSubset<T, TasksCollectionCreateArgs<ExtArgs>>): Prisma.Prisma__TasksCollectionClient<runtime.Types.Result.GetResult<Prisma.$TasksCollectionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TasksCollections.
   * @param {TasksCollectionCreateManyArgs} args - Arguments to create many TasksCollections.
   * @example
   * // Create many TasksCollections
   * const tasksCollection = await prisma.tasksCollection.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TasksCollectionCreateManyArgs>(args?: Prisma.SelectSubset<T, TasksCollectionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TasksCollections and returns the data saved in the database.
   * @param {TasksCollectionCreateManyAndReturnArgs} args - Arguments to create many TasksCollections.
   * @example
   * // Create many TasksCollections
   * const tasksCollection = await prisma.tasksCollection.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TasksCollections and only return the `tasksId`
   * const tasksCollectionWithTasksIdOnly = await prisma.tasksCollection.createManyAndReturn({
   *   select: { tasksId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TasksCollectionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TasksCollectionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TasksCollectionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TasksCollection.
   * @param {TasksCollectionDeleteArgs} args - Arguments to delete one TasksCollection.
   * @example
   * // Delete one TasksCollection
   * const TasksCollection = await prisma.tasksCollection.delete({
   *   where: {
   *     // ... filter to delete one TasksCollection
   *   }
   * })
   * 
   */
  delete<T extends TasksCollectionDeleteArgs>(args: Prisma.SelectSubset<T, TasksCollectionDeleteArgs<ExtArgs>>): Prisma.Prisma__TasksCollectionClient<runtime.Types.Result.GetResult<Prisma.$TasksCollectionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TasksCollection.
   * @param {TasksCollectionUpdateArgs} args - Arguments to update one TasksCollection.
   * @example
   * // Update one TasksCollection
   * const tasksCollection = await prisma.tasksCollection.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TasksCollectionUpdateArgs>(args: Prisma.SelectSubset<T, TasksCollectionUpdateArgs<ExtArgs>>): Prisma.Prisma__TasksCollectionClient<runtime.Types.Result.GetResult<Prisma.$TasksCollectionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TasksCollections.
   * @param {TasksCollectionDeleteManyArgs} args - Arguments to filter TasksCollections to delete.
   * @example
   * // Delete a few TasksCollections
   * const { count } = await prisma.tasksCollection.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TasksCollectionDeleteManyArgs>(args?: Prisma.SelectSubset<T, TasksCollectionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TasksCollections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TasksCollectionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TasksCollections
   * const tasksCollection = await prisma.tasksCollection.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TasksCollectionUpdateManyArgs>(args: Prisma.SelectSubset<T, TasksCollectionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TasksCollections and returns the data updated in the database.
   * @param {TasksCollectionUpdateManyAndReturnArgs} args - Arguments to update many TasksCollections.
   * @example
   * // Update many TasksCollections
   * const tasksCollection = await prisma.tasksCollection.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TasksCollections and only return the `tasksId`
   * const tasksCollectionWithTasksIdOnly = await prisma.tasksCollection.updateManyAndReturn({
   *   select: { tasksId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TasksCollectionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TasksCollectionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TasksCollectionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TasksCollection.
   * @param {TasksCollectionUpsertArgs} args - Arguments to update or create a TasksCollection.
   * @example
   * // Update or create a TasksCollection
   * const tasksCollection = await prisma.tasksCollection.upsert({
   *   create: {
   *     // ... data to create a TasksCollection
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TasksCollection we want to update
   *   }
   * })
   */
  upsert<T extends TasksCollectionUpsertArgs>(args: Prisma.SelectSubset<T, TasksCollectionUpsertArgs<ExtArgs>>): Prisma.Prisma__TasksCollectionClient<runtime.Types.Result.GetResult<Prisma.$TasksCollectionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TasksCollections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TasksCollectionCountArgs} args - Arguments to filter TasksCollections to count.
   * @example
   * // Count the number of TasksCollections
   * const count = await prisma.tasksCollection.count({
   *   where: {
   *     // ... the filter for the TasksCollections we want to count
   *   }
   * })
  **/
  count<T extends TasksCollectionCountArgs>(
    args?: Prisma.Subset<T, TasksCollectionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TasksCollectionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TasksCollection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TasksCollectionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TasksCollectionAggregateArgs>(args: Prisma.Subset<T, TasksCollectionAggregateArgs>): Prisma.PrismaPromise<GetTasksCollectionAggregateType<T>>

  /**
   * Group by TasksCollection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TasksCollectionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TasksCollectionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TasksCollectionGroupByArgs['orderBy'] }
      : { orderBy?: TasksCollectionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TasksCollectionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTasksCollectionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TasksCollection model
 */
readonly fields: TasksCollectionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TasksCollection.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TasksCollectionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tasks<T extends Prisma.TasksCollection$tasksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TasksCollection$tasksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TasksCollection model
 */
export interface TasksCollectionFieldRefs {
  readonly tasksId: Prisma.FieldRef<"TasksCollection", 'String'>
  readonly tasksName: Prisma.FieldRef<"TasksCollection", 'String'>
  readonly details: Prisma.FieldRef<"TasksCollection", 'String'>
  readonly created: Prisma.FieldRef<"TasksCollection", 'DateTime'>
  readonly due: Prisma.FieldRef<"TasksCollection", 'DateTime'>
  readonly updated: Prisma.FieldRef<"TasksCollection", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TasksCollection findUnique
 */
export type TasksCollectionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TasksCollection
   */
  select?: Prisma.TasksCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TasksCollection
   */
  omit?: Prisma.TasksCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TasksCollectionInclude<ExtArgs> | null
  /**
   * Filter, which TasksCollection to fetch.
   */
  where: Prisma.TasksCollectionWhereUniqueInput
}

/**
 * TasksCollection findUniqueOrThrow
 */
export type TasksCollectionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TasksCollection
   */
  select?: Prisma.TasksCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TasksCollection
   */
  omit?: Prisma.TasksCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TasksCollectionInclude<ExtArgs> | null
  /**
   * Filter, which TasksCollection to fetch.
   */
  where: Prisma.TasksCollectionWhereUniqueInput
}

/**
 * TasksCollection findFirst
 */
export type TasksCollectionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TasksCollection
   */
  select?: Prisma.TasksCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TasksCollection
   */
  omit?: Prisma.TasksCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TasksCollectionInclude<ExtArgs> | null
  /**
   * Filter, which TasksCollection to fetch.
   */
  where?: Prisma.TasksCollectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TasksCollections to fetch.
   */
  orderBy?: Prisma.TasksCollectionOrderByWithRelationInput | Prisma.TasksCollectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TasksCollections.
   */
  cursor?: Prisma.TasksCollectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TasksCollections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TasksCollections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TasksCollections.
   */
  distinct?: Prisma.TasksCollectionScalarFieldEnum | Prisma.TasksCollectionScalarFieldEnum[]
}

/**
 * TasksCollection findFirstOrThrow
 */
export type TasksCollectionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TasksCollection
   */
  select?: Prisma.TasksCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TasksCollection
   */
  omit?: Prisma.TasksCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TasksCollectionInclude<ExtArgs> | null
  /**
   * Filter, which TasksCollection to fetch.
   */
  where?: Prisma.TasksCollectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TasksCollections to fetch.
   */
  orderBy?: Prisma.TasksCollectionOrderByWithRelationInput | Prisma.TasksCollectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TasksCollections.
   */
  cursor?: Prisma.TasksCollectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TasksCollections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TasksCollections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TasksCollections.
   */
  distinct?: Prisma.TasksCollectionScalarFieldEnum | Prisma.TasksCollectionScalarFieldEnum[]
}

/**
 * TasksCollection findMany
 */
export type TasksCollectionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TasksCollection
   */
  select?: Prisma.TasksCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TasksCollection
   */
  omit?: Prisma.TasksCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TasksCollectionInclude<ExtArgs> | null
  /**
   * Filter, which TasksCollections to fetch.
   */
  where?: Prisma.TasksCollectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TasksCollections to fetch.
   */
  orderBy?: Prisma.TasksCollectionOrderByWithRelationInput | Prisma.TasksCollectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TasksCollections.
   */
  cursor?: Prisma.TasksCollectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TasksCollections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TasksCollections.
   */
  skip?: number
  distinct?: Prisma.TasksCollectionScalarFieldEnum | Prisma.TasksCollectionScalarFieldEnum[]
}

/**
 * TasksCollection create
 */
export type TasksCollectionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TasksCollection
   */
  select?: Prisma.TasksCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TasksCollection
   */
  omit?: Prisma.TasksCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TasksCollectionInclude<ExtArgs> | null
  /**
   * The data needed to create a TasksCollection.
   */
  data: Prisma.XOR<Prisma.TasksCollectionCreateInput, Prisma.TasksCollectionUncheckedCreateInput>
}

/**
 * TasksCollection createMany
 */
export type TasksCollectionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TasksCollections.
   */
  data: Prisma.TasksCollectionCreateManyInput | Prisma.TasksCollectionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TasksCollection createManyAndReturn
 */
export type TasksCollectionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TasksCollection
   */
  select?: Prisma.TasksCollectionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TasksCollection
   */
  omit?: Prisma.TasksCollectionOmit<ExtArgs> | null
  /**
   * The data used to create many TasksCollections.
   */
  data: Prisma.TasksCollectionCreateManyInput | Prisma.TasksCollectionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TasksCollection update
 */
export type TasksCollectionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TasksCollection
   */
  select?: Prisma.TasksCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TasksCollection
   */
  omit?: Prisma.TasksCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TasksCollectionInclude<ExtArgs> | null
  /**
   * The data needed to update a TasksCollection.
   */
  data: Prisma.XOR<Prisma.TasksCollectionUpdateInput, Prisma.TasksCollectionUncheckedUpdateInput>
  /**
   * Choose, which TasksCollection to update.
   */
  where: Prisma.TasksCollectionWhereUniqueInput
}

/**
 * TasksCollection updateMany
 */
export type TasksCollectionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TasksCollections.
   */
  data: Prisma.XOR<Prisma.TasksCollectionUpdateManyMutationInput, Prisma.TasksCollectionUncheckedUpdateManyInput>
  /**
   * Filter which TasksCollections to update
   */
  where?: Prisma.TasksCollectionWhereInput
  /**
   * Limit how many TasksCollections to update.
   */
  limit?: number
}

/**
 * TasksCollection updateManyAndReturn
 */
export type TasksCollectionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TasksCollection
   */
  select?: Prisma.TasksCollectionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TasksCollection
   */
  omit?: Prisma.TasksCollectionOmit<ExtArgs> | null
  /**
   * The data used to update TasksCollections.
   */
  data: Prisma.XOR<Prisma.TasksCollectionUpdateManyMutationInput, Prisma.TasksCollectionUncheckedUpdateManyInput>
  /**
   * Filter which TasksCollections to update
   */
  where?: Prisma.TasksCollectionWhereInput
  /**
   * Limit how many TasksCollections to update.
   */
  limit?: number
}

/**
 * TasksCollection upsert
 */
export type TasksCollectionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TasksCollection
   */
  select?: Prisma.TasksCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TasksCollection
   */
  omit?: Prisma.TasksCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TasksCollectionInclude<ExtArgs> | null
  /**
   * The filter to search for the TasksCollection to update in case it exists.
   */
  where: Prisma.TasksCollectionWhereUniqueInput
  /**
   * In case the TasksCollection found by the `where` argument doesn't exist, create a new TasksCollection with this data.
   */
  create: Prisma.XOR<Prisma.TasksCollectionCreateInput, Prisma.TasksCollectionUncheckedCreateInput>
  /**
   * In case the TasksCollection was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TasksCollectionUpdateInput, Prisma.TasksCollectionUncheckedUpdateInput>
}

/**
 * TasksCollection delete
 */
export type TasksCollectionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TasksCollection
   */
  select?: Prisma.TasksCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TasksCollection
   */
  omit?: Prisma.TasksCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TasksCollectionInclude<ExtArgs> | null
  /**
   * Filter which TasksCollection to delete.
   */
  where: Prisma.TasksCollectionWhereUniqueInput
}

/**
 * TasksCollection deleteMany
 */
export type TasksCollectionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TasksCollections to delete
   */
  where?: Prisma.TasksCollectionWhereInput
  /**
   * Limit how many TasksCollections to delete.
   */
  limit?: number
}

/**
 * TasksCollection.tasks
 */
export type TasksCollection$tasksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskInclude<ExtArgs> | null
  where?: Prisma.TaskWhereInput
  orderBy?: Prisma.TaskOrderByWithRelationInput | Prisma.TaskOrderByWithRelationInput[]
  cursor?: Prisma.TaskWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TaskScalarFieldEnum | Prisma.TaskScalarFieldEnum[]
}

/**
 * TasksCollection without action
 */
export type TasksCollectionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TasksCollection
   */
  select?: Prisma.TasksCollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TasksCollection
   */
  omit?: Prisma.TasksCollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TasksCollectionInclude<ExtArgs> | null
}
